import jsPDF from "jspdf";
import type { StudyNotes } from "@/components/NotesPreview";

export function generatePDF(notes: StudyNotes, videoUrl: string) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let y = 20;

  const checkPage = (needed: number) => {
    if (y + needed > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage();
      y = 20;
    }
  };

  // Title
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  const titleLines = doc.splitTextToSize(notes.title, maxWidth);
  doc.text(titleLines, margin, y);
  y += titleLines.length * 10 + 5;

  // Source
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text(`Source: ${videoUrl}`, margin, y);
  y += 6;
  doc.text(`Generated by StudyTube AI — ${new Date().toLocaleDateString()}`, margin, y);
  doc.setTextColor(0, 0, 0);
  y += 12;

  // Summary
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Summary", margin, y);
  y += 8;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const summaryLines = doc.splitTextToSize(notes.summary, maxWidth);
  checkPage(summaryLines.length * 5);
  doc.text(summaryLines, margin, y);
  y += summaryLines.length * 5 + 10;

  // Key Points
  checkPage(15);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Key Points", margin, y);
  y += 8;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  for (const point of notes.keyPoints) {
    const lines = doc.splitTextToSize(`• ${point}`, maxWidth - 5);
    checkPage(lines.length * 5 + 3);
    doc.text(lines, margin + 3, y);
    y += lines.length * 5 + 3;
  }
  y += 7;

  // Study Notes
  checkPage(15);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Study Notes", margin, y);
  y += 8;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  for (const note of notes.notes) {
    const lines = doc.splitTextToSize(`• ${note}`, maxWidth - 5);
    checkPage(lines.length * 5 + 3);
    doc.text(lines, margin + 3, y);
    y += lines.length * 5 + 3;
  }
  y += 7;

  // Definitions
  if (notes.definitions.length > 0) {
    checkPage(15);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Key Definitions", margin, y);
    y += 8;
    for (const def of notes.definitions) {
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      const termLines = doc.splitTextToSize(`${def.term}:`, maxWidth);
      checkPage(termLines.length * 5 + 8);
      doc.text(termLines, margin + 3, y);
      y += termLines.length * 5;
      doc.setFont("helvetica", "normal");
      const defLines = doc.splitTextToSize(def.definition, maxWidth - 8);
      doc.text(defLines, margin + 6, y);
      y += defLines.length * 5 + 4;
    }
    y += 7;
  }

  // Quiz
  if (notes.quizQuestions.length > 0) {
    checkPage(15);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Quiz Questions", margin, y);
    y += 8;
    for (let i = 0; i < notes.quizQuestions.length; i++) {
      const q = notes.quizQuestions[i];
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      const qLines = doc.splitTextToSize(`${i + 1}. ${q.question}`, maxWidth);
      checkPage(qLines.length * 5 + q.options.length * 5 + 12);
      doc.text(qLines, margin + 3, y);
      y += qLines.length * 5 + 2;
      doc.setFont("helvetica", "normal");
      q.options.forEach((opt, j) => {
        doc.text(`${String.fromCharCode(65 + j)}. ${opt}`, margin + 8, y);
        y += 5;
      });
      doc.setFontSize(9);
      doc.setTextColor(0, 128, 100);
      doc.text(`Answer: ${q.answer}`, margin + 8, y);
      doc.setTextColor(0, 0, 0);
      y += 8;
    }
  }

  doc.save(`${notes.title.replace(/[^a-zA-Z0-9]/g, "_")}_StudyNotes.pdf`);
}
